ALTER TABLE public.crushes
  ADD COLUMN IF NOT EXISTS review TEXT,
  ADD COLUMN IF NOT EXISTS had_chat_rating SMALLINT NOT NULL DEFAULT 0 CHECK (had_chat_rating BETWEEN 0 AND 5),
  ADD COLUMN IF NOT EXISTS had_kiss_rating SMALLINT NOT NULL DEFAULT 0 CHECK (had_kiss_rating BETWEEN 0 AND 5),
  ADD COLUMN IF NOT EXISTS had_pirulito_rating SMALLINT NOT NULL DEFAULT 0 CHECK (had_pirulito_rating BETWEEN 0 AND 5),
  ADD COLUMN IF NOT EXISTS had_donut_rating SMALLINT NOT NULL DEFAULT 0 CHECK (had_donut_rating BETWEEN 0 AND 5),
  ADD COLUMN IF NOT EXISTS had_fire_rating SMALLINT NOT NULL DEFAULT 0 CHECK (had_fire_rating BETWEEN 0 AND 5);
